export const SETTING_DOCUMENTS = 'SETTING_DOCUMENTS';
export const SETTING_DOCUMENTS_SUCCESS = 'SETTING_DOCUMENTS_SUCCESS';
export const SETTING_DOCUMENTS_FAIL = 'SETTING_DOCUMENTS_FAIL';

export const SETTING_JOBS = 'SETTING_JOBS';
export const SETTING_JOBS_SUCCESS = 'SETTING_JOBS_SUCCESS';
export const SETTING_JOBS_FAIL = 'SETTING_JOBS_FAIL';

export const SETTING_STATS = 'SETTING_STATS';
export const SETTING_STATS_SUCCESS = 'SETTING_STATS_SUCCESS';
export const SETTING_STATS_FAIL = 'SETTING_STATS_FAIL';

export const SETTING_PERFORMANCE = 'SETTING_PERFORMANCE';
export const SETTING_PERFORMANCE_SUCCESS = 'SETTING_PERFORMANCE_SUCCESS';
export const SETTING_PERFORMANCE_FAIL = 'SETTING_PERFORMANCE_FAIL';

export const SETTING_LIBRARY = 'SETTING_LIBRARY';
export const SETTING_LIBRARY_SUCCESS = 'SETTING_LIBRARY_SUCCESS';
export const SETTING_LIBRARY_FAIL = 'SETTING_LIBRARY_FAIL';

export const RUNNING_NLPQL = 'RUNNING_NLPQL';
export const RUNNING_NLPQL_SUCCESS = 'RUNNING_NLPQL_SUCCESS';
export const RUNNING_NLPQL_FAIL = 'RUNNING_NLPQL_FAIL';

export const DELETING_QUERY = 'DELETING_QUERY';
export const DELETING_QUERY_SUCCESS = 'DELETING_QUERY_SUCCESS';
export const DELETING_QUERY_FAIL = 'DELETING_QUERY_FAIL';
