export const SETTING_DOCUMENTS = "SETTING_DOCUMENTS";
export const SETTING_DOCUMENTS_SUCCESS = "SETTING_DOCUMENTS_SUCCESS";
export const SETTING_DOCUMENTS_FAIL = "SETTING_DOCUMENTS_FAIL";

export const SETTING_JOBS = "SETTING_JOBS";
export const SETTING_JOBS_SUCCESS = "SETTING_JOBS_SUCCESS";
export const SETTING_JOBS_FAIL = "SETTING_JOBS_FAIL";
